mqtt:
  enabled: false

cameras:
  doorbell_high_res:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASSWORD}@{FRIGATE_DOORBELL_IP}:554
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASSWORD}@{FRIGATE_DOORBELL_IP}:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
  g3_bedroom:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{CAMERA1_IP}:7447/{CAMERA1_WIDE}
          roles:
            - record
        - path: rtsp://{CAMERA1_IP}:7447/{CAMERA1_SMALL}
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1024
      height: 576
record:
  enabled: true
  retain:
    days: 14
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
detectors:
  coral:
    type: edgetpu
    device: pci:0

snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 30
    objects:
      person: 365

version: 0.16-0
detect:
  enabled: true
