mqtt:
  enabled: false

cameras:
  doorbell_high_res:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASSWORD}@10.0.0.84:554
          roles:
            - record
        - path: rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASSWORD}@10.0.0.84:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
  g3_bedroom:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/YYYY?enableSrtp
          roles:
            - record
        - path: rtsp://192.168.1.1:7447/XXXX?enableSrtp
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1024
      height: 576
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: motion

detectors:
  coral:
    type: edgetpu
    device: pci:0

snapshots:
  enabled: True
  timestamp: True
  retain:
    default: 30
    objects:
      person: 365

version: 0.14
