version: "3.9" # template from https://docs.frigate.video/guides/getting_started/
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    env_file:
      - frigate/frigate.env
    volumes:
      - /var/lib/NVR_docker/automation/frigate/config:/config
      - /nvr_disk:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/apex_0:/dev/apex_0
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
